'use client'

import React, { useCallback, useMemo, useState } from 'react'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Bot, Download, Maximize2, User } from 'lucide-react'
import { ImageLightbox } from '@/components/ui/ImageLightbox'

interface ChatMessageProps {
  type: 'text' | 'image'
  content?: string
  caption?: string
  imageUrl?: string
  isUser: boolean
  timestamp: Date
  imagePreviewUrl?: string
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function renderBasicMarkdown(md: string): string {
  // Minimal, safe-ish Markdown to HTML for headings, lists, paragraphs, and code fences.
  const text = escapeHtml(md)
  const lines = text.split(/\r?\n/)
  const html: string[] = []
  let inUL = false
  let inCode = false

  for (const line of lines) {
    if (line.trim().startsWith('```')) {
      if (!inCode) {
        html.push('<pre><code>')
        inCode = true
      } else {
        html.push('</code></pre>')
        inCode = false
      }
      continue
    }

    if (inCode) {
      html.push(line)
      continue
    }

    if (/^###\s+/.test(line)) {
      if (inUL) {
        html.push('</ul>')
        inUL = false
      }
      html.push('<h3>' + line.replace(/^###\s+/, '') + '</h3>')
      continue
    }
    if (/^##\s+/.test(line)) {
      if (inUL) {
        html.push('</ul>')
        inUL = false
      }
      html.push('<h2>' + line.replace(/^##\s+/, '') + '</h2>')
      continue
    }
    if (/^#\s+/.test(line)) {
      if (inUL) {
        html.push('</ul>')
        inUL = false
      }
      html.push('<h1>' + line.replace(/^#\s+/, '') + '</h1>')
      continue
    }

    if (/^\s*[-*]\s+/.test(line)) {
      if (!inUL) {
        html.push('<ul>')
        inUL = true
      }
      html.push('<li>' + line.replace(/^\s*[-*]\s+/, '') + '</li>')
      continue
    }

    if (line.trim() === '') {
      if (inUL) {
        html.push('</ul>')
        inUL = false
      }
      continue
    }

    html.push('<p>' + line + '</p>')
  }

  if (inUL) html.push('</ul>')
  if (inCode) html.push('</code></pre>')
  return html.join('\n')
}

const HEX_COLOR_REGEX = /#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})(?![0-9a-fA-F])/g

function expandHex(hex: string): string {
  if (hex.length === 4) {
    const [, r, g, b] = hex.split('')
    return `#${r}${r}${g}${g}${b}${b}`.toUpperCase()
  }
  return hex.toUpperCase()
}

function addColorSwatches(html: string): string {
  return html.replace(HEX_COLOR_REGEX, (match) => {
    const expanded = expandHex(match)
    return `<span class="inline-flex items-center gap-2 rounded-full bg-slate-100 px-2 py-1 text-[11px] font-medium text-slate-700 shadow-sm" title="${expanded}"><span class="inline-block h-4 w-4 rounded-md border border-black/20 shadow-inner" style="background-color:${expanded}"></span><span class="font-mono tracking-tight">${expanded}</span></span>`
  })
}

export function ChatMessage({ type, content, caption, imageUrl, isUser, timestamp, imagePreviewUrl }: ChatMessageProps) {
  const textContent = content ?? ''
  const assistantHtml = useMemo(
    () => (content ? addColorSwatches(renderBasicMarkdown(content)) : ''),
    [content],
  )
  const showImage = !isUser && type === 'image' && Boolean(imageUrl)
  const showCaption = Boolean(!isUser && caption && (!content || caption.trim() !== content.trim()))
  const altText = caption || 'Outfit generated by Echo Shop'
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [lightboxSrc, setLightboxSrc] = useState<string | null>(null)
  const [lightboxCaption, setLightboxCaption] = useState<string | undefined>(undefined)

  const handleOpenLightbox = useCallback(() => {
    if (!imageUrl) return
    setLightboxSrc(imageUrl)
    setLightboxCaption(caption)
    setLightboxOpen(true)
  }, [caption, imageUrl])

  const handleCloseLightbox = useCallback(() => {
    setLightboxOpen(false)
    setLightboxSrc(null)
    setLightboxCaption(undefined)
  }, [])

  const handleDownload = useCallback(() => {
    if (!imageUrl) return
    const extension = imageUrl.split('?')[0].toLowerCase().match(/\.(png|jpe?g|webp)$/)?.[1] ?? 'png'
    const formattedTime = timestamp.toISOString().replace(/[:.]/g, '-')
    const filename = `echo-shop-outfit-${formattedTime}.${extension}`
    const anchor = document.createElement('a')
    anchor.href = imageUrl
    anchor.download = filename
    document.body.appendChild(anchor)
    anchor.click()
    document.body.removeChild(anchor)
  }, [imageUrl, timestamp])

  return (
    <div className={`flex items-start space-x-3 min-w-0 ${isUser ? 'flex-row-reverse space-x-reverse' : ''}`}>
      <Avatar className="w-8 h-8">
        <AvatarFallback className={isUser ? 'bg-blue-500 text-white' : 'bg-purple-500 text-white'}>
          {isUser ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
        </AvatarFallback>
      </Avatar>

      <div
        className={`relative inline-block max-w-full md:max-w-2xl lg:max-w-3xl px-4 py-3 rounded-lg shadow-sm break-words min-w-0 ${
          isUser ? 'bg-blue-500 text-white ml-auto self-end' : 'bg-gray-100 text-gray-900 self-start'
        }`}
        style={{ overflowWrap: 'break-word', wordBreak: 'break-word' }}
      >
        {imagePreviewUrl && (
          <img src={imagePreviewUrl} alt="attached" className="mb-2 rounded max-h-40" />
        )}

        {isUser ? (
          <p className="text-sm whitespace-pre-line break-words leading-relaxed">{textContent}</p>
        ) : (
          <div className="space-y-3">
            {showImage && imageUrl && (
              <figure className="overflow-hidden rounded-lg border border-slate-200 bg-slate-100">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={imageUrl}
                  alt={altText}
                  className="max-h-96 w-full object-cover transition-transform duration-150 hover:scale-[1.01]"
                />
                <figcaption className="flex items-center justify-between gap-3 border-t border-slate-200 bg-white px-3 py-2">
                  <div className="flex flex-wrap items-center gap-2">
                    <button
                      type="button"
                      onClick={handleOpenLightbox}
                      className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 px-2.5 py-1 text-[11px] font-medium text-slate-600 transition hover:border-purple-300 hover:text-purple-600"
                    >
                      <Maximize2 className="h-3.5 w-3.5" />
                      <span>Preview</span>
                    </button>
                    <button
                      type="button"
                      onClick={handleDownload}
                      className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 px-2.5 py-1 text-[11px] font-medium text-slate-600 transition hover:border-purple-300 hover:text-purple-600"
                    >
                      <Download className="h-3.5 w-3.5" />
                      <span>Download</span>
                    </button>
                  </div>
                  <span className="text-[11px] text-slate-400">
                    {timestamp.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                  </span>
                </figcaption>
              </figure>
            )}
            {showCaption && caption && (
              <p className="text-sm font-medium text-gray-900">{caption}</p>
            )}
            {content && (
              <div
                className="text-sm leading-relaxed whitespace-pre-line break-words space-y-2 [&>p]:m-0 [&>ul]:list-disc [&>ul]:pl-5 [&>ul]:mt-1 [&>li]:mt-1 [&>h1]:text-base [&>h1]:font-semibold [&>h1]:mt-0 [&>h1]:mb-1 [&>h2]:text-base [&>h2]:font-semibold [&>h2]:mt-0 [&>h2]:mb-1 [&>h3]:text-sm [&>h3]:font-semibold [&>h3]:mt-0 [&>h3]:mb-1"
                dangerouslySetInnerHTML={{ __html: assistantHtml }}
              />
            )}
          </div>
        )}

        <p className={`text-xs mt-1 ${isUser ? 'text-blue-100' : 'text-gray-500'}`}>
          {timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </p>
      </div>
      <ImageLightbox open={lightboxOpen} imageUrl={lightboxSrc ?? undefined} caption={lightboxCaption} onClose={handleCloseLightbox} />
    </div>
  )
}

